// docs/.vitepress/theme/components/NewHomePage/Footer.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { isServer } from '../../utils/i18n'

const { t, locale } = useI18n()

const isCN = computed(() => !isServer() && window.location.host.endsWith('.cn'))

const beianText = computed(() =>
  isCN.value && locale.value === 'zh-CN' ? `© ${new Date().getFullYear()} 粤 ICP 备 2025433117 号` : '',
)

const sgBaseUrl = computed(() =>
  locale.value === 'en' ? 'https://longbridge.com/sg' : 'https://longbridge.com/sg/zh-CN',
)

const leftLinks = computed(() => [
  { href: 'https://longbridge.com', label: 'Longbridge' },
  { href: 'https://longbridge.com/download', label: 'Download' },
  {
    href: `${sgBaseUrl.value}/support/topics/us-trade/user-agreement`,
    label: t('side-footer.section-terms.terms-of-service'),
  },
  {
    href: `${sgBaseUrl.value}/support/topics/Other/privacy-policy`,
    label: t('side-footer.section-terms.privacy-policy'),
  },
])

const rightLinks = [
  { href: '/sdk', label: 'SDK' },
  { href: '/docs/mcp', label: 'MCP' },
  { href: '/docs/cli', label: 'CLI' },
  { href: '/docs/llm', label: 'LLM' },
  { href: 'https://github.com/longbridge/developers/issues', label: 'Feedback' },
]
</script>

<template>
  <footer v-if="!isCN" class="nhp-footer">
    <div class="nhp-footer-inner">
      <div class="nhp-footer-left">
        <a v-if="beianText" class="nhp-link" href="https://beian.miit.gov.cn/" rel="nofollow">
          {{ beianText }}
        </a>
        <a
          v-for="link in leftLinks"
          :key="link.href"
          :href="link.href"
          class="nhp-link"
          :target="link.href.startsWith('/') ? '_self' : '_blank'">
          {{ link.label }}
        </a>
      </div>
      <div class="nhp-footer-right">
        <a
          v-for="link in rightLinks"
          :key="link.href"
          :href="link.href"
          class="nhp-link"
          :target="link.href.startsWith('/') ? '_self' : '_blank'">
          {{ link.label }}
        </a>
        <a href="https://github.com/longbridge" class="nhp-github" target="_blank" aria-label="GitHub">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="15" height="15">
            <path
              d="M12.001 2C6.47598 2 2.00098 6.475 2.00098 12C2.00098 16.425 4.86348 20.1625 8.83848 21.4875C9.33848 21.575 9.52598 21.275 9.52598 21.0125C9.52598 20.775 9.51348 19.9875 9.51348 19.15C7.00098 19.6125 6.35098 18.5375 6.15098 17.975C6.03848 17.6875 5.55098 16.8 5.12598 16.5625C4.77598 16.375 4.27598 15.9125 5.11348 15.9C5.90098 15.8875 6.46348 16.625 6.65098 16.925C7.55098 18.4375 8.98848 18.0125 9.56348 17.75C9.65098 17.1 9.91348 16.6625 10.201 16.4125C7.97598 16.1625 5.65098 15.3 5.65098 11.475C5.65098 10.3875 6.03848 9.4875 6.67598 8.7875C6.57598 8.5375 6.22598 7.5125 6.77598 6.1375C6.77598 6.1375 7.61348 5.875 9.52598 7.1625C10.326 6.9375 11.176 6.825 12.026 6.825C12.876 6.825 13.726 6.9375 14.526 7.1625C16.4385 5.8625 17.276 6.1375 17.276 6.1375C17.826 7.5125 17.476 8.5375 17.376 8.7875C18.0135 9.4875 18.401 10.375 18.401 11.475C18.401 15.3125 16.0635 16.1625 13.8385 16.4125C14.201 16.725 14.5135 17.325 14.5135 18.2625C14.5135 19.6 14.501 20.675 14.501 21.0125C14.501 21.275 14.6885 21.5875 15.1885 21.4875C19.259 20.1133 21.9999 16.2963 22.001 12C22.001 6.475 17.526 2 12.001 2Z" />
          </svg>
        </a>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.nhp-footer {
  border-top: 1px solid var(--vp-c-divider);
  padding: 1.25rem 1.5rem;
}

.nhp-footer-inner {
  max-width: 64rem;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.nhp-footer-left,
.nhp-footer-right {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 1rem;
}

.nhp-link {
  font-size: 0.75rem;
  color: var(--vp-c-text-3);
  text-decoration: none;
  transition: color 0.15s;
  white-space: nowrap;
}

.nhp-link:hover {
  color: var(--vp-c-text-1);
}

.nhp-github {
  display: inline-flex;
  align-items: center;
  color: var(--vp-c-text-3);
  transition: color 0.15s;
}

.nhp-github:hover {
  color: var(--vp-c-text-1);
}
</style>

// src/components/shell/Footer.tsx
import { t } from '@longbridge/openapi-utils'
import type { Locale } from '@longbridge/openapi-utils'

interface Props {
  locale: Locale
}

const LOGO_LIGHT =
  'https://assets.lbkrs.com/uploads/e76f6d93-80f8-4f9b-8b8d-2c86f0c94a78/longbridge-developers-light.png'
const LOGO_DARK =
  'https://assets.lbkrs.com/uploads/37a18fa4-46a4-408c-a36a-560004eb3cfb/longbridge-developers-dark.png'

function localePath(locale: Locale, path: string): string {
  if (locale === 'en') return path
  return `/${locale}${path}`
}

function sgBaseUrl(locale: Locale): string {
  return locale === 'en' ? 'https://longbridge.com/sg' : 'https://longbridge.com/sg/zh-CN'
}

export default function Footer({ locale }: Props) {
  const year = new Date().getFullYear()
  const base = sgBaseUrl(locale)
  const homeHref = locale === 'en' ? '/' : `/${locale}/`

  return (
    <footer className="border-t border-[color:var(--lb-stroke)] text-[color:var(--lb-fg-2)] text-sm py-8 px-4 mt-16" data-lbus-component="footer">
      <div className="max-w-[80rem] mx-auto grid gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-[1.5fr_repeat(4,1fr)]">
        {/* Brand column */}
        <div className="flex flex-col gap-2 col-span-full lg:col-auto">
          <a href={homeHref} className="inline-flex items-center gap-2 text-[color:var(--lbus-c-text)] no-underline" aria-label="Longbridge Developers">
            <img
              className="h-6 w-auto block [[data-mode='dark']_&]:hidden"
              src={LOGO_LIGHT}
              alt="Longbridge Developers"
            />
            <img
              className="h-6 w-auto hidden [[data-mode='dark']_&]:inline-block"
              src={LOGO_DARK}
              alt="Longbridge Developers"
            />
          </a>
          <p>{t(locale, 'footer.tagline')}</p>
          <div className="inline-flex items-center gap-[0.4rem] text-[color:var(--lb-fg-2)] text-[0.8rem]">
            <span
              style={{
                width: 6,
                height: 6,
                borderRadius: 999,
                background: 'var(--lb-up)',
                boxShadow: '0 0 0 3px color-mix(in srgb, var(--lb-up) 25%, transparent)',
                flexShrink: 0,
                display: 'inline-block',
              }}
            />
            <span>{t(locale, 'footer.status')}</span>
          </div>
        </div>

        {/* Products */}
        <div>
          <h5 className="text-[0.7rem] font-semibold uppercase tracking-[0.06em] mb-3 mt-0 text-[color:var(--lbus-c-text)]">{t(locale, 'footer.products')}</h5>
          <ul className="list-none p-0 m-0 flex flex-col gap-[0.35rem]">
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/skill')}>AI Skill</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/cli')}>CLI</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/mcp')}>MCP</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/llm')}>LLMs</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href="https://navi-lang.org" target="_blank" rel="noreferrer">Navi</a></li>
          </ul>
        </div>

        {/* Resources */}
        <div>
          <h5 className="text-[0.7rem] font-semibold uppercase tracking-[0.06em] mb-3 mt-0 text-[color:var(--lbus-c-text)]">{t(locale, 'footer.resources')}</h5>
          <ul className="list-none p-0 m-0 flex flex-col gap-[0.35rem]">
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/getting-started')}>{t(locale, 'footer.gettingStarted')}</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs')}>Documentation</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/assets')}>{t(locale, 'footer.assets')}</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/quote/pull/quote')}>Quote API</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/trade/order/submit')}>Trade API</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/changelog')}>{t(locale, 'footer.changelog')}</a></li>
            <li>
              <a
                className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]"
                href="https://github.com/longbridge/developers/issues"
                target="_blank"
                rel="noreferrer"
              >
                {t(locale, 'footer.feedback')}
              </a>
            </li>
          </ul>
        </div>

        {/* Company */}
        <div>
          <h5 className="text-[0.7rem] font-semibold uppercase tracking-[0.06em] mb-3 mt-0 text-[color:var(--lbus-c-text)]">{t(locale, 'footer.company')}</h5>
          <ul className="list-none p-0 m-0 flex flex-col gap-[0.35rem]">
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href="https://longbridge.com" target="_blank" rel="noreferrer">Longbridge</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href="https://longbridge.com/download" target="_blank" rel="noreferrer">{t(locale, 'footer.download')}</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href="https://status.longbridge.com" target="_blank" rel="noreferrer">{t(locale, 'footer.statusPage')}</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href="https://longbridge.com/about" target="_blank" rel="noreferrer">{t(locale, 'footer.about')}</a></li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href="https://github.com/longbridge" target="_blank" rel="noreferrer">GitHub</a></li>
          </ul>
        </div>

        {/* Legal */}
        <div>
          <h5 className="text-[0.7rem] font-semibold uppercase tracking-[0.06em] mb-3 mt-0 text-[color:var(--lbus-c-text)]">{t(locale, 'footer.legal')}</h5>
          <ul className="list-none p-0 m-0 flex flex-col gap-[0.35rem]">
            <li>
              <a
                className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]"
                href={`${base}/support/topics/us-trade/user-agreement`}
                target="_blank"
                rel="noreferrer"
              >
                {t(locale, 'footer.terms')}
              </a>
            </li>
            <li>
              <a
                className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]"
                href={`${base}/support/topics/Other/privacy-policy`}
                target="_blank"
                rel="noreferrer"
              >
                {t(locale, 'footer.privacy')}
              </a>
            </li>
            <li><a className="text-[color:var(--lb-fg-2)] no-underline text-[0.85rem] hover:text-[color:var(--lb-brand)]" href={localePath(locale, '/docs/legal')}>{t(locale, 'footer.agreements')}</a></li>
          </ul>
        </div>
      </div>

      <div className="border-t border-[color:var(--lb-stroke)] pt-4 flex flex-wrap gap-4 items-center justify-between">
        <div>{t(locale, 'footer.rights', { year })}</div>
        <div className="flex flex-wrap gap-4">
          <span style={{ color: 'var(--lb-fg-3)' }}>·</span>
          <a className="text-[color:var(--lb-fg-2)] no-underline hover:text-[color:var(--lb-brand)]" href="/">English</a>
          <a className="text-[color:var(--lb-fg-2)] no-underline hover:text-[color:var(--lb-brand)]" href="/zh-CN/">简体中文</a>
          <a className="text-[color:var(--lb-fg-2)] no-underline hover:text-[color:var(--lb-brand)]" href="/zh-HK/">繁體中文</a>
        </div>
      </div>
    </footer>
  )
}
