// src/components/mdx/McpTools.tsx
/**
 * McpTools.tsx
 * Port of McpTools.vue → React, for MDX pages.
 * Data source: .data/mcp-tools.json (written at build time by
 *   src/integrations/prebuild-mcp-tools.ts which fetches from
 *   https://mcp.longbridge.com/mcp/tools.json).
 * Locale: MDX pages don't inject a locale prop, so locale defaults to 'en'.
 */
import { useRef, useState, useEffect } from 'react'
import mcpToolsData from '../../../.data/mcp-tools.json'
import './McpTools.css'

// ── Types ─────────────────────────────────────────────────────────────────────

interface SchemaProperty {
  type: string | string[]
  description?: string
  enum?: string[]
  default?: unknown
  format?: string
  minimum?: number
  maximum?: number
}

interface ToolSchema {
  properties?: Record<string, SchemaProperty>
  required?: string[]
}

interface Tool {
  name: string
  description: string
  inputSchema?: ToolSchema
}

interface ToolsPayload {
  tools: Tool[]
}

interface ParamRow {
  name: string
  type: string
  required: boolean
  description?: string
  enum?: string[]
  default?: unknown
}

// ── Inline i18n (keys also added to locale files) ────────────────────────────

const STRINGS: Record<string, Record<string, string>> = {
  en: {
    searchPlaceholder: 'Search tools…',
    clearSearch: 'Clear search',
    noMatch: 'No tools match "{query}"',
    noParams: 'No parameters.',
    params: 'Parameters',
    required: 'required',
    enum: 'Enum',
    default: 'Default',
  },
  'zh-CN': {
    searchPlaceholder: '搜索工具…',
    clearSearch: '清除搜索',
    noMatch: '没有匹配 "{query}" 的工具',
    noParams: '无参数。',
    params: '参数',
    required: '必填',
    enum: '枚举',
    default: '默认',
  },
  'zh-HK': {
    searchPlaceholder: '搜尋工具…',
    clearSearch: '清除搜尋',
    noMatch: '沒有符合「{query}」的工具',
    noParams: '無參數。',
    params: '參數',
    required: '必填',
    enum: '枚舉',
    default: '預設',
  },
}

function tStr(locale: string, key: string, vars?: Record<string, string>): string {
  const dict = STRINGS[locale] ?? STRINGS['en']
  let str = dict[key] ?? STRINGS['en'][key] ?? key
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(`{${k}}`, v)
    }
  }
  return str
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatType(type: string | string[]): string {
  return Array.isArray(type) ? type.join(' | ') : type
}

function getParams(schema?: ToolSchema): ParamRow[] {
  if (!schema?.properties) return []
  const required = new Set(schema.required ?? [])
  return Object.entries(schema.properties).map(([name, def]) => ({
    name,
    type: formatType(def.type),
    required: required.has(name),
    description: def.description,
    enum: def.enum,
    default: def.default,
  }))
}

// ── SVG Icons ─────────────────────────────────────────────────────────────────

const SearchIcon = () => (
  <svg
    className="mcp-tools-search-icon"
    xmlns="http://www.w3.org/2000/svg"
    width="16"
    height="16"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <circle cx="11" cy="11" r="8" />
    <line x1="21" y1="21" x2="16.65" y2="16.65" />
  </svg>
)

const ClearIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
)

const WrenchIcon = ({ open }: { open: boolean }) => (
  <svg
    className={`mcp-tool-icon${open ? ' mcp-tool-icon--open' : ''}`}
    xmlns="http://www.w3.org/2000/svg"
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
  </svg>
)

const ChevronIcon = () => (
  <svg
    className="mcp-accordion-chevron"
    xmlns="http://www.w3.org/2000/svg"
    width="12"
    height="12"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <polyline points="9 18 15 12 9 6" />
  </svg>
)

// ── Accordion Item ─────────────────────────────────────────────────────────────

interface AccordionItemProps {
  tool: Tool
  isOpen: boolean
  onToggle: () => void
  locale: string
}

function AccordionItem({ tool, isOpen, onToggle, locale }: AccordionItemProps) {
  const params = getParams(tool.inputSchema)
  const contentRef = useRef<HTMLDivElement>(null)

  return (
    <div
      className="mcp-accordion-item"
      data-state={isOpen ? 'open' : 'closed'}
    >
      <button
        type="button"
        className="mcp-accordion-trigger"
        data-state={isOpen ? 'open' : 'closed'}
        onClick={onToggle}
        aria-expanded={isOpen}
      >
        <span className="mcp-tool-title">
          <WrenchIcon open={isOpen} />
          <code className="mcp-tool-name">{tool.name}</code>
        </span>
        <ChevronIcon />
      </button>

      <div
        ref={contentRef}
        className="mcp-accordion-content"
        data-state={isOpen ? 'open' : 'closed'}
        hidden={!isOpen}
      >
        <div className="mcp-accordion-content-inner">
          <p className="mcp-tool-desc">{tool.description}</p>

          {params.length === 0 ? (
            <p className="mcp-tool-no-params">{tStr(locale, 'noParams')}</p>
          ) : (
            <>
              <h4 className="mcp-params-title">{tStr(locale, 'params')}</h4>
              <dl className="mcp-params">
                {params.map((p) => (
                  <div key={p.name} className="mcp-param">
                    <dt className="mcp-param-head">
                      <code className="mcp-param-name">{p.name}</code>
                      <span className="mcp-param-type">{p.type}</span>
                      {p.required && (
                        <span className="mcp-param-required">
                          {tStr(locale, 'required')}
                        </span>
                      )}
                    </dt>
                    <dd className="mcp-param-body">
                      {p.description && (
                        <p className="mcp-param-desc">{p.description}</p>
                      )}
                      {p.enum && (
                        <p className="mcp-param-meta">
                          {tStr(locale, 'enum')}: {p.enum.map((e) => `"${e}"`).join(' | ')}
                        </p>
                      )}
                      {p.default !== undefined && (
                        <p className="mcp-param-meta">
                          {tStr(locale, 'default')}: {String(p.default)}
                        </p>
                      )}
                    </dd>
                  </div>
                ))}
              </dl>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Main Component ─────────────────────────────────────────────────────────────

export interface McpToolsProps {
  locale?: string
}

export function McpTools({ locale = 'en' }: McpToolsProps) {
  const allTools: Tool[] = (mcpToolsData as unknown as ToolsPayload).tools

  const [query, setQuery] = useState('')
  const [openValue, setOpenValue] = useState<string>('')
  const listRef = useRef<HTMLDivElement>(null)

  // Scroll open item into view after accordion animation settles (~220ms)
  useEffect(() => {
    if (!openValue || !listRef.current) return
    const timer = setTimeout(() => {
      const container = listRef.current
      if (!container) return
      const openItem = container.querySelector<HTMLElement>(
        '.mcp-accordion-item[data-state="open"]'
      )
      if (!openItem) return
      const itemTop =
        openItem.getBoundingClientRect().top -
        container.getBoundingClientRect().top +
        container.scrollTop
      const itemBottom = itemTop + openItem.offsetHeight
      const visibleTop = container.scrollTop
      const visibleBottom = visibleTop + container.clientHeight
      if (itemTop >= visibleTop && itemBottom <= visibleBottom) return
      container.scrollTo({ top: itemTop, behavior: 'smooth' })
    }, 220)
    return () => clearTimeout(timer)
  }, [openValue])

  const q = query.trim().toLowerCase()
  const filtered = q
    ? allTools.filter(
        (t) =>
          t.name.toLowerCase().includes(q) ||
          t.description.toLowerCase().includes(q)
      )
    : allTools

  function handleToggle(name: string) {
    setOpenValue((prev) => (prev === name ? '' : name))
  }

  return (
    <div className="mcp-tools" data-lbus-component="mcp-tools">
      <div className="mcp-tools-search">
        <div className="mcp-tools-input-wrap">
          <SearchIcon />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="mcp-tools-input"
            placeholder={tStr(locale, 'searchPlaceholder')}
          />
          {query && (
            <button
              type="button"
              className="mcp-tools-clear"
              aria-label={tStr(locale, 'clearSearch')}
              onClick={() => setQuery('')}
            >
              <ClearIcon />
            </button>
          )}
        </div>
      </div>

      {filtered.length === 0 ? (
        <div className="mcp-tools-empty">
          {tStr(locale, 'noMatch', { query: query.trim() })}
        </div>
      ) : (
        <div ref={listRef} className="mcp-tools-list">
          {filtered.map((tool) => (
            <AccordionItem
              key={tool.name}
              tool={tool}
              isOpen={openValue === tool.name}
              onToggle={() => handleToggle(tool.name)}
              locale={locale}
            />
          ))}
        </div>
      )}
    </div>
  )
}

// docs/.vitepress/theme/components/McpTools.vue
<script setup lang="ts">
import { ref, computed, nextTick, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import toolsData from '../../data/mcp-tools.json'
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from './ui/accordion'

interface SchemaProperty {
  type: string | string[]
  description?: string
  enum?: string[]
  default?: unknown
  format?: string
  minimum?: number
  maximum?: number
}

interface ToolSchema {
  properties?: Record<string, SchemaProperty>
  required?: string[]
}

interface Tool {
  name: string
  description: string
  inputSchema?: ToolSchema
}

interface ToolsPayload {
  tools: Tool[]
}

interface ParamRow {
  name: string
  type: string
  required: boolean
  description?: string
  enum?: string[]
  default?: unknown
  format?: string
}

const { t } = useI18n()

const allTools: Tool[] = (toolsData as ToolsPayload).tools

const query = ref('')
const openValue = ref<string>('')
const listRef = ref<HTMLElement | null>(null)

watch(openValue, async (v) => {
  if (!v || !listRef.value) return
  await nextTick()
  // Wait for accordion slide-down/up animation (~200ms) to settle
  // before measuring — otherwise the previously open item still
  // occupies its pre-collapse space and offsets are wrong.
  await new Promise((resolve) => setTimeout(resolve, 220))
  const container = listRef.value
  if (!container) return
  const openItem = container.querySelector<HTMLElement>(
    '.mcp-accordion-item[data-state="open"]'
  )
  if (!openItem) return
  const itemTop =
    openItem.getBoundingClientRect().top -
    container.getBoundingClientRect().top +
    container.scrollTop
  const itemBottom = itemTop + openItem.offsetHeight
  const visibleTop = container.scrollTop
  const visibleBottom = visibleTop + container.clientHeight
  if (itemTop >= visibleTop && itemBottom <= visibleBottom) return
  container.scrollTo({ top: itemTop, behavior: 'smooth' })
})

const filtered = computed<Tool[]>(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return allTools
  return allTools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q)
  )
})

function formatType(type: string | string[]): string {
  return Array.isArray(type) ? type.join(' | ') : type
}

function getParams(schema?: ToolSchema): ParamRow[] {
  if (!schema?.properties) return []
  const required = new Set(schema.required ?? [])
  return Object.entries(schema.properties).map(([name, def]) => ({
    name,
    type: formatType(def.type),
    required: required.has(name),
    description: def.description,
    enum: def.enum,
    default: def.default,
    format: def.format,
  }))
}
</script>

<template>
  <div class="mcp-tools">
    <div class="mcp-tools-search">
      <div class="mcp-tools-input-wrap">
        <svg
          class="mcp-tools-search-icon"
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
        >
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>
        <input
          v-model="query"
          type="text"
          class="mcp-tools-input"
          :placeholder="t('mcp.searchPlaceholder')"
        />
        <button
          v-if="query"
          type="button"
          class="mcp-tools-clear"
          :aria-label="t('mcp.clearSearch')"
          @click="query = ''"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>
    </div>

    <div v-if="filtered.length === 0" class="mcp-tools-empty">
      {{ t('mcp.noMatch', { query }) }}
    </div>

    <div v-else ref="listRef" class="mcp-tools-list">
    <Accordion v-model="openValue" type="single" collapsible>
      <template v-for="(tool, idx) in filtered" :key="tool.name">
      <div
        v-if="tool.name.startsWith('screener_') && (idx === 0 || !filtered[idx - 1].name.startsWith('screener_'))"
        class="mcp-screener-note"
      >{{ t('mcp.screenerNotePrefix') }}<a href="https://longbridge.com/screener" target="_blank" rel="noreferrer">{{ t('mcp.screenerNoteLinkText') }}</a>{{ t('mcp.screenerNoteSuffix') }}</div>
      <AccordionItem
        :value="tool.name"
      >
        <AccordionTrigger>
          <span class="mcp-tool-title">
            <svg
              class="mcp-tool-icon"
              xmlns="http://www.w3.org/2000/svg"
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
            </svg>
            <code class="mcp-tool-name">{{ tool.name }}</code>
          </span>
        </AccordionTrigger>
        <AccordionContent>
          <p class="mcp-tool-desc">{{ tool.description }}</p>

          <p v-if="getParams(tool.inputSchema).length === 0" class="mcp-tool-no-params">
            {{ t('mcp.noParams') }}
          </p>

          <template v-else>
            <h4 class="mcp-params-title">{{ t('mcp.params') }}</h4>
            <dl class="mcp-params">
              <div
                v-for="p in getParams(tool.inputSchema)"
                :key="p.name"
                class="mcp-param"
              >
                <dt class="mcp-param-head">
                  <code class="mcp-param-name">{{ p.name }}</code>
                  <span class="mcp-param-type">{{ p.type }}</span>
                  <span v-if="p.required" class="mcp-param-required">{{ t('mcp.required') }}</span>
                </dt>
                <dd class="mcp-param-body">
                  <p v-if="p.description" class="mcp-param-desc">{{ p.description }}</p>
                  <p v-if="p.enum" class="mcp-param-meta">
                    {{ t('mcp.enum') }}: {{ p.enum.map((e) => `"${e}"`).join(' | ') }}
                  </p>
                  <p v-if="p.default !== undefined" class="mcp-param-meta">
                    {{ t('mcp.default') }}: {{ p.default }}
                  </p>
                </dd>
              </div>
            </dl>
          </template>
        </AccordionContent>
      </AccordionItem>
      </template>
    </Accordion>
    </div>
  </div>
</template>

<style scoped>
.mcp-tools {
  margin: 1rem 0;
}

.mcp-tools-search {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-bottom: 0.75rem;
  padding-bottom: 0.5rem;
  position: sticky;
  top: var(--vp-nav-height, 64px);
  z-index: 1;
  background: var(--vp-c-bg);
}

.mcp-tools-input-wrap {
  width: 320px;
  max-width: 100%;
  position: relative;
  display: flex;
  align-items: center;
}

.mcp-tools-search-icon {
  position: absolute;
  left: 0.75rem;
  color: var(--vp-c-text-3);
  pointer-events: none;
  transition: color 0.15s ease;
}

.mcp-tools-input {
  width: 100%;
  padding: 0.55rem 2.25rem 0.55rem 2.25rem;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  background: transparent;
  color: var(--vp-c-text-1);
  font-size: 0.9rem;
  line-height: 1.25;
  outline: none;
}

.mcp-tools-input::placeholder {
  color: var(--vp-c-text-3);
}

.mcp-tools-clear {
  position: absolute;
  right: 0.5rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 1.5rem;
  height: 1.5rem;
  padding: 0;
  border: 0;
  border-radius: 4px;
  background: transparent;
  color: var(--vp-c-text-3);
  cursor: pointer;
  transition: color 0.15s ease, background 0.15s ease;
}

.mcp-tools-clear:hover {
  color: var(--vp-c-text-1);
  background: var(--vp-c-default-soft);
}


.mcp-tools-empty {
  padding: 1rem;
  text-align: center;
  color: var(--vp-c-text-2);
  font-size: 0.9rem;
}

.mcp-tools-list {
  border: 1px solid var(--vp-c-divider);
  border-radius: 6px;
  max-height: 500px;
  overflow-y: auto;
  padding: 0 0.75rem;
}

.mcp-tools-list :deep(.mcp-accordion-item:last-child) {
  border-bottom: 0;
}

.mcp-tool-title {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
}

.mcp-tool-icon {
  color: var(--vp-c-text-3);
  flex-shrink: 0;
}

.mcp-tools-list :deep(.mcp-accordion-trigger[data-state='open']) .mcp-tool-icon {
  color: var(--vp-c-brand-1);
}

.mcp-tool-name {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, monospace;
  font-size: 1rem;
  color: var(--vp-c-text-1);
  background: transparent;
  padding: 0;
}

.mcp-tools-list :deep(.mcp-accordion-trigger) {
  padding: 0.5rem 0;
  font-size: 1rem;
}

.mcp-tool-desc {
  margin: 0 0 0.5rem;
  color: var(--vp-c-text-2);
  font-size: 0.75rem;
}

.mcp-tool-no-params {
  margin: 0;
  color: var(--vp-c-text-3);
  font-style: italic;
  font-size: 0.75rem;
}

.mcp-params-title {
  margin: 0 0 0.35rem;
  font-size: 0.75rem;
  font-weight: 400;
  color: var(--vp-c-text-2);
}

.mcp-params {
  margin: 0;
  padding: 0;
}

.mcp-param {
  padding: 0.3rem 0;
}
.mcp-param:first-child {
  padding-top: 0;
}
.mcp-param:last-child {
  padding-bottom: 0;
}

.mcp-param-head {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: 0.4rem;
  margin: 0 0 0.2rem;
}

.mcp-param-name {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, monospace;
  font-size: 0.75rem;
  color: var(--vp-c-text-1);
  background: var(--vp-c-bg-soft);
  padding: 0.05rem 0.35rem;
  border-radius: 4px;
}

.mcp-param-type {
  font-size: 0.75rem;
  color: var(--vp-c-text-2);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, monospace;
}

.mcp-param-required {
  font-size: 0.75rem;
  color: var(--vp-c-text-2);
  background: var(--vp-c-bg-soft);
  padding: 0.08rem 0.35rem;
  border-radius: 4px;
}

.mcp-param-body {
  margin: 0;
  padding-left: 0;
}

.mcp-param-desc {
  margin: 0;
  color: var(--vp-c-text-2);
  font-size: 0.75rem;
  line-height: 1.45;
}

.mcp-param-meta {
  margin: 0;
  color: var(--vp-c-text-3);
  font-size: 0.75rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, monospace;
}

.mcp-screener-note {
  margin: 0.75rem 0 0.5rem;
  padding: 0.5rem 0.75rem;
  font-size: 0.8rem;
  color: var(--vp-c-text-2);
  background: var(--vp-c-bg-soft);
  border-left: 3px solid var(--vp-c-brand-1);
  border-radius: 0 4px 4px 0;
}

.mcp-screener-note a {
  color: var(--vp-c-brand-1);
  text-decoration: none;
}

.mcp-screener-note a:hover {
  text-decoration: underline;
}
</style>
