// packages/homepage/src/sections/CoreFeaturesSection.tsx
import React from 'react'
import type { Locale } from '@longbridge/openapi-utils'

const LOCALE = {
  en: {
    title: 'Developer Tools',
    subtitle: 'Everything you need to build, test, and ship financial applications',
    products: {
      cli: {
        title: 'CLI',
        desc: 'AI-native terminal tool with interactive TUI dashboard, 130+ commands, and --format json output for scripting and AI agent integration.',
      },
      skill: {
        title: 'AI Skill',
        desc: 'Use Longbridge in ChatGPT Apps with @longbridge, or give Skill-compatible agents real-time quotes, portfolio data, news sentiment, and market intelligence.',
      },
      mcp: {
        title: 'MCP',
        desc: 'Official ChatGPT App plus hosted OAuth 2.1 MCP for Codex, Claude Code, Cursor, Zed, and Cherry Studio.',
      },
      sdk: {
        title: 'SDK',
        desc: 'Get your first quote in minutes. 7 languages — Python, Node.js, Rust, Go, Java, C, C++ — with async support and built-in rate control.',
      },
      paper: {
        title: 'Paper Trading',
        desc: 'Test orders with real market data at zero cost. Simulated matching based on live bid-ask spreads, no securities account required.',
      },
      llm: {
        title: 'LLM Ready',
        desc: 'llms.txt standard compliance, all docs available as .md for RAG pipelines, and Accept: text/markdown header support on longbridge.com.',
      },
    } as Record<string, { title: string; desc: string }>,
  },
  'zh-CN': {
    title: '开发者工具',
    subtitle: '构建、测试和发布金融应用所需的一切',
    products: {
      cli: {
        title: 'CLI',
        desc: 'AI 原生终端工具，配备交互式 TUI 面板、130+ 命令、--format json 输出，支持脚本和 AI Agent 集成。',
      },
      skill: {
        title: 'AI Skill',
        desc: '在 ChatGPT Apps 中通过 @longbridge 使用 Longbridge，也可为兼容 Skill 的 Agent 提供实时行情、组合数据、新闻情绪和市场洞察。',
      },
      mcp: {
        title: 'MCP',
        desc: '官方 ChatGPT App，加上面向 Codex、Claude Code、Cursor、Zed 和 Cherry Studio 的托管 OAuth 2.1 MCP。',
      },
      sdk: {
        title: 'SDK',
        desc: '分钟内获取第一个行情。7 种语言 — Python、Node.js、Rust、Go、Java、C、C++ — 内置异步和频率控制。',
      },
      paper: { title: '模拟交易', desc: '使用真实行情数据零成本测试下单。模拟撮合基于实时买卖盘价格，无需证券账户。' },
      llm: {
        title: 'LLM 就绪',
        desc: '遵循 llms.txt 标准，所有文档支持 .md 后缀 RAG 管道接入，longbridge.com 支持 Accept: text/markdown。',
      },
    } as Record<string, { title: string; desc: string }>,
  },
  'zh-HK': {
    title: '開發者工具',
    subtitle: '構建、測試和發佈金融應用所需的一切',
    products: {
      cli: {
        title: 'CLI',
        desc: 'AI 原生終端工具，配備互動式 TUI 面板、130+ 命令、--format json 輸出，支援腳本和 AI Agent 集成。',
      },
      skill: {
        title: 'AI Skill',
        desc: '在 ChatGPT Apps 中透過 @longbridge 使用 Longbridge，也可為兼容 Skill 的 Agent 提供即時行情、組合數據、新聞情緒和市場洞察。',
      },
      mcp: {
        title: 'MCP',
        desc: '官方 ChatGPT App，加上面向 Codex、Claude Code、Cursor、Zed 和 Cherry Studio 的託管 OAuth 2.1 MCP。',
      },
      sdk: {
        title: 'SDK',
        desc: '分鐘內獲取第一個行情。7 種語言 — Python、Node.js、Rust、Go、Java、C、C++ — 內置異步和頻率控制。',
      },
      paper: { title: '模擬交易', desc: '使用真實行情數據零成本測試下單。模擬撮合基於即時買賣盤價格，無需證券賬戶。' },
      llm: {
        title: 'LLM 就緒',
        desc: '遵循 llms.txt 標準，所有文檔支持 .md 後綴 RAG 管道接入，longbridge.com 支持 Accept: text/markdown。',
      },
    } as Record<string, { title: string; desc: string }>,
  },
}

const icons: Record<string, string> = {
  cli: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/></svg>`,
  skill: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a4 4 0 014 4v1a1 1 0 001 1h1a4 4 0 010 8h-1a1 1 0 00-1 1v1a4 4 0 01-8 0v-1a1 1 0 00-1-1H6a4 4 0 010-8h1a1 1 0 001-1V6a4 4 0 014-4z"/><circle cx="12" cy="12" r="2"/></svg>`,
  mcp: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M12 1v6m0 6v6m-7-3.5l5.2-3m1.6-1l5.2-3M5 6.5l5.2 3m1.6 1l5.2 3"/></svg>`,
  sdk: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 18l6-6-6-6"/><path d="M8 6l-6 6 6 6"/></svg>`,
  paper: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="15" x2="15" y2="15"/></svg>`,
  llm: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>`,
}

const tags: Record<string, string[]> = {
  cli: ['TUI', '--format json'],
  skill: ['AI Agent'],
  mcp: ['OAuth 2.1', 'Hosted'],
  sdk: ['Python', 'Rust', 'Go', '+ 4'],
  paper: ['Sandbox', 'Zero Cost'],
  llm: ['Markdown', 'llms.txt'],
}

const links: Record<string, string> = {
  cli: '/docs/cli',
  skill: '/skill',
  mcp: '/docs/mcp',
  sdk: '/sdk',
  paper: '/docs/getting-started',
  llm: '/docs/llm',
}

const accents: Record<string, string> = {
  skill: '#00dbb6',
  cli: '#fc5200',
  mcp: '#3b82f6',
  sdk: '#22c55e',
  paper: '#f59e0b',
  llm: '#a855f7',
}

const products = ['skill', 'cli', 'mcp', 'sdk', 'paper', 'llm']

const CORE_CSS = `
.core-section {
  padding: 4rem 0;
  background: var(--vp-c-bg);
}
.core-header {
  text-align: center;
  margin-bottom: 2.5rem;
  padding: 0 1.5rem;
}
.core-title {
  font-size: 1.75rem;
  font-weight: 700;
  color: var(--vp-c-text-1);
  letter-spacing: -0.02em;
}
.core-subtitle {
  margin-top: 24px;
  color: var(--vp-c-text-2);
}
.core-icon {
  display: flex;
  width: 1.5rem;
  height: 1.5rem;
  flex-shrink: 0;
}
.core-icon svg {
  width: 100%;
  height: 100%;
}
.core-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem;
}
.core-tag {
  padding: 0.15rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.62rem;
  font-weight: 600;
  font-family: var(--vp-font-family-mono);
}
.core-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.25rem;
  max-width: 64rem;
  margin: 0 auto;
  padding: 0 1.5rem;
}
@media (max-width: 900px) {
  .core-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}
@media (max-width: 480px) {
  .core-grid {
    grid-template-columns: 1fr;
  }
}
.core-card {
  position: relative;
  border-radius: 1rem;
  border: 1px solid var(--vp-c-divider);
  text-decoration: none !important;
  overflow: hidden;
  isolation: isolate;
  transition: transform 220ms cubic-bezier(0.2, 0.8, 0.2, 1), box-shadow 220ms cubic-bezier(0.2, 0.8, 0.2, 1), border-color 220ms;
}
:root.dark .core-card {
  border-color: color-mix(in srgb, var(--vp-c-divider) 80%, transparent);
}
.core-card:hover {
  transform: translateY(-3px);
  box-shadow: 0 16px 36px -10px rgba(10, 14, 25, 0.13), 0 3px 12px -5px rgba(10, 14, 25, 0.06);
}
.core-card-inner {
  position: relative;
  z-index: 1;
  padding: 1.75rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  min-height: 12rem;
}
.core-card-top {
  display: flex;
  align-items: center;
  gap: 0.625rem;
}
.core-card-title {
  font-size: 0.95rem;
  font-weight: 700;
  color: var(--vp-c-text-1);
}
.core-card-desc {
  font-size: 0.875rem;
  line-height: 1.6;
  color: var(--vp-c-text-2);
  margin: 0;
  flex: 1;
}
`

interface CoreFeaturesSectionProps {
  locale: Locale
}

export function CoreFeaturesSection({ locale }: CoreFeaturesSectionProps) {
  const content = LOCALE[locale] ?? LOCALE.en
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: CORE_CSS }} />
      <section data-lbus-component="core-features" className="core-section">
        <div className="core-header">
          <h2 className="core-title">{content.title}</h2>
          <p className="core-subtitle">{content.subtitle}</p>
        </div>
        <div className="core-grid">
          {products.map((key) => {
            const accent = accents[key]
            return (
              <a
                key={key}
                href={links[key]}
                className="core-card"
                style={
                  {
                    '--card-accent': accent,
                    background: `radial-gradient(280px 140px at 100% 0%, color-mix(in srgb, ${accent} 9%, transparent), transparent 70%), var(--vp-c-bg)`,
                    borderColor: undefined,
                  } as React.CSSProperties
                }
              >
                <div className="core-card-inner">
                  <div className="core-card-top">
                    <span
                      className="core-icon"
                      style={{ color: accent }}
                      dangerouslySetInnerHTML={{ __html: icons[key] }}
                    />
                    <span className="core-card-title">{content.products[key]?.title}</span>
                  </div>
                  <p className="core-card-desc">{content.products[key]?.desc}</p>
                  <div className="core-tags">
                    {(tags[key] ?? []).map((tag) => (
                      <span
                        key={tag}
                        className="core-tag"
                        style={{
                          background: `color-mix(in srgb, ${accent} 10%, transparent)`,
                          color: accent,
                        }}
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              </a>
            )
          })}
        </div>
      </section>
    </>
  )
}

// docs/.vitepress/theme/components/NewHomePage/CoreFeaturesSection.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const icons = {
  cli: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/></svg>`,
  skill: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a4 4 0 014 4v1a1 1 0 001 1h1a4 4 0 010 8h-1a1 1 0 00-1 1v1a4 4 0 01-8 0v-1a1 1 0 00-1-1H6a4 4 0 010-8h1a1 1 0 001-1V6a4 4 0 014-4z"/><circle cx="12" cy="12" r="2"/></svg>`,
  mcp: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M12 1v6m0 6v6m-7-3.5l5.2-3m1.6-1l5.2-3M5 6.5l5.2 3m1.6 1l5.2 3"/></svg>`,
  sdk: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 18l6-6-6-6"/><path d="M8 6l-6 6 6 6"/></svg>`,
  paper: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="15" x2="15" y2="15"/></svg>`,
  llm: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>`,
}

const tags: Record<string, string[]> = {
  cli: ['TUI', '--format json'],
  skill: ['AI Agent'],
  mcp: ['OAuth 2.1', 'Hosted'],
  sdk: ['Python', 'Rust', 'Go', '+ 4'],
  paper: ['Sandbox', 'Zero Cost'],
  llm: ['Markdown', 'llms.txt'],
}

const links: Record<string, string> = {
  cli: '/docs/cli',
  skill: '/skill',
  mcp: '/docs/mcp',
  sdk: '/sdk',
  paper: '/docs/getting-started',
  llm: '/docs/llm',
}

const accents: Record<string, string> = {
  skill: '#00dbb6',
  cli: '#fc5200',
  mcp: '#6366f1',
  sdk: '#00b8b8',
  paper: '#f59e0b',
  llm: '#a855f7',
}

const products = ['skill', 'cli', 'mcp', 'sdk', 'paper', 'llm']
</script>

<template>
  <section class="core-section">
    <div class="core-header">
      <h2 class="core-title">{{ $t('core.title') }}</h2>
      <p class="core-subtitle">{{ $t('core.subtitle') }}</p>
    </div>

    <div class="core-grid">
      <a
        v-for="key in products"
        :key="key"
        :href="links[key]"
        class="core-card"
        :style="{
          '--card-accent': accents[key],
          background: `radial-gradient(280px 140px at 100% 0%, color-mix(in srgb, ${accents[key]} 9%, transparent), transparent 70%), var(--vp-c-bg)`,
        }">
        <div class="core-card-inner">
          <div class="core-card-top">
            <span class="core-icon" :style="{ color: accents[key] }" v-html="icons[key as keyof typeof icons]" />
            <span class="core-card-title">{{ $t(`core.${key}.title`) }}</span>
          </div>
          <p class="core-card-desc">{{ $t(`core.${key}.desc`) }}</p>
          <div class="core-tags">
            <span
              v-for="tag in tags[key]"
              :key="tag"
              class="core-tag"
              :style="{
                background: `color-mix(in srgb, ${accents[key]} 10%, transparent)`,
                color: accents[key],
              }">{{ tag }}</span>
          </div>
        </div>
      </a>
    </div>
  </section>
</template>

<style scoped>
.core-section {
  padding: 4rem 0;
  background: var(--vp-c-bg);
}
.core-header {
  text-align: center;
  margin-bottom: 2.5rem;
  padding: 0 1.5rem;
}
.core-title {
  font-size: 1.75rem;
  font-weight: 700;
  color: var(--vp-c-text-1);
  letter-spacing: -0.02em;
}
.core-subtitle {
  margin-top: 24px;
  color: var(--vp-c-text-2);
}

.core-icon {
  display: flex;
  width: 1.5rem;
  height: 1.5rem;
  flex-shrink: 0;
}
.core-icon :deep(svg) {
  width: 100%;
  height: 100%;
}

.core-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem;
}
.core-tag {
  padding: 0.15rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.62rem;
  font-weight: 600;
  font-family: var(--vp-font-family-mono);
}

/* Grid */
.core-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.25rem;
  max-width: 64rem;
  margin: 0 auto;
  padding: 0 1.5rem;
}
@media (max-width: 900px) {
  .core-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}
@media (max-width: 480px) {
  .core-grid {
    grid-template-columns: 1fr;
  }
}

.core-card {
  position: relative;
  border-radius: 1rem;
  border: 1px solid var(--vp-c-divider);
  text-decoration: none !important;
  overflow: hidden;
  isolation: isolate;
  transition: transform 220ms cubic-bezier(0.2, 0.8, 0.2, 1), box-shadow 220ms cubic-bezier(0.2, 0.8, 0.2, 1), border-color 220ms;
}
:root.dark .core-card {
  border-color: color-mix(in srgb, var(--vp-c-divider) 80%, transparent);
}
.core-card:hover {
  border-color: color-mix(in srgb, var(--card-accent, var(--brand-color)) 50%, var(--vp-c-divider));
  transform: translateY(-3px);
  box-shadow: 0 16px 36px -10px rgba(10, 14, 25, 0.13), 0 3px 12px -5px rgba(10, 14, 25, 0.06);
}

.core-card-inner {
  position: relative;
  z-index: 1;
  padding: 1.75rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  min-height: 12rem;
}
.core-card-top {
  display: flex;
  align-items: center;
  gap: 0.625rem;
}
.core-card-title {
  font-size: 0.95rem;
  font-weight: 700;
  color: var(--vp-c-text-1);
}
.core-card-desc {
  font-size: 0.875rem;
  line-height: 1.6;
  color: var(--vp-c-text-2);
  margin: 0;
  flex: 1;
}
</style>
